# Generated by Django 4.1.3 on 2022-11-17 09:19

from django.db import migrations
import json


def copy_places_to_db(apps, schema_editor):
    with open("static/places/moscow_legends.json", "r") as file:
        place1_json = file.read()

    with open("static/places/roofs24.json", "r") as file:
        place2_json = file.read()

    place1 = json.loads(place1_json)
    place2 = json.loads(place2_json)
    places = [place1, place2]

    Place = apps.get_model('poster', 'Place')

    for place in places:
        Place.objects.get_or_create(
            title=place['title'],
            description_short=place['description_short'],
            description_long=place['description_long'],
            lng=place['coordinates']['lng'],
            lat=place['coordinates']['lat'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_places_to_db),
    ]
