# Generated by Django 4.1.3 on 2022-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=250, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
