# Generated by Django 4.1.3 on 2022-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_alter_place_description_short_alter_place_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='позиция'),
        ),
    ]
